### ISSUE TITLE
listing a large directory fails

### ISSUE THREAD

**Issue by reflog** [38leinaD/tango#3]
inside _tango_TRANS2_FIND_FIRST2, if the response is rather large, the server returns only part of the data. 
so the check:
    if (resp_total_data_count != resp_data_count) {
will fail, since  (resp_total_data_count > resp_data_count) 

any suggestions on how to fix?

**Comment by 38leinaD** [comment]
The Transaction2 protocol defines that in this case additional response-SMBs will be sent by the server. This is currently not handled by _tango_TRANS2_FIND_FIRST2.
Details are defined in CIFS-TR-1p00_FINAL.pdf pages 32f + 37.

Might have a look at it when there is time.

**Comment by reflog** [comment]
Thanks for the info, I'll read up a bit on it.. Maybe you have some implementation pointers? (in case I'll get brave to take a crack at it myself)

In any case, hope you'll get back to working on the project some more, so far you've done a great job, it's the first liberally licensed SMB implementation I know, and also nicely and clean written, it has a potential to become a very useful tool!

Thanks for your hard work!

**Comment by 38leinaD** [comment]
thanks for the nice words. the problem to get back working on it is always that this protocol such a mess; you can easily see how this protocol evolved over the years...

In case you want to have bad dreams at night ;-), here are some hints:
- basically, this Transacion2-protocol (from which the FIND2_FIRST SMB is example) defines that a first Transaction2 SMB as described on the listed pages is sent to the server and a full response is sent back; that is what i have implemented currently (as this is the only SMB at the moment using this Transaction2 protocol, nothing is factored out to a common place but all found in this one method)
- In the error-case described by you, the server would actually be sending some additional responses with a secondary Transaction2-response; this one (see the pages) does not have all the fields as in the first response; so, if you would evaluate also those responses, you might have to have a look at the message definition and see what fields are defined and strip some parts
- I general, when getting in the condition
  
  if (resp_total_data_count != resp_data_count)

you would call _tango_receive() (see tango_Echo.c) as long this condition is true; after each received block, you would evaluate the SMB like it is now already done after the _tango_send_and_receive call (only according to the secondary Transaction2 response message-format); and the secondary Find2_First response seems also to have less field.

Let me know if my words make any sense...

**Comment by reflog** [comment]
that does make sense... basically, that piece of code should be turned from 'if' into a 'while'... i'll try to get a crack at it next week.

again, thanks for you help, hope you'll get some more time/energy to work on this beast of a protocol!

**Comment by vguevara** [comment]
First of all, I agree with reflog, you have done a great job by making tango available. It is great to see some progress on supporting external shares in the iPhone.

I am facing the same problem, though, but from a different perspective. I 'extended' the library by inserting a couple of operations to retrieve a know file location (\host\share\path\to\my\file\hurray.txt) by traversing the FileInfo objects. I noticed my operations where returning nil (actually an error) mysteriously in specific directories. The problem was that some directories did not return the right fileInfo because of the issue (resp_total_data_count > resp_data_count).

I was wondering if anyone came with a (tangible) solution. I would prefer keeping my hands clean before diving into the SMB/CIFS protocol. Anyway, I will try to implement the solut..., I mean, an artifact and post it here.

**Comment by vguevara** [comment]
These are the operation I added. Basically, my idea was to get the FileInfo from a 'filepath' and use the result to read the file. I didn't need the browse capabilities and I know the location of the files.

This works to certain extend. There are however some directories that do not report any files when trying to list them. I thought the problem was related to the topic of this issue. However, the code never reaches the original comparison (resp_total_data_count != resp_data_count) and rather fails when the response is evaluated with (_tango_smb_getParametersSize(smb) == 0).

I guessed there was another message but when I try to evaluate I got _tango_evaluate_response_header(): NT_STATUS Level is 0003 with value 006d.

These are the operations...
'''
//Returns the fileInfo related to the filename or nil if it was not found
- (tangoFileInfo *)fileInfoFromName:(NSString *)filename inFolder:(tangoFileInfo *) folderInfo {
  tangoFileInfo *toReturn = nil;
  
  NSArray *fileArray = [self listDirectory:folderInfo];
  
  for (tangoFileInfo *fileDescriptor in fileArray) {
      if ([filename isEqualToString:[fileDescriptor name]]) {
          return fileDescriptor;
      }
  }
  return toReturn;
  }

//Returns the fileInfo related to the filepath
- (tangoFileInfo *)fileInfoFromPath:(NSString *)filename {
  NSArray *chunks = [filename componentsSeparatedByString:@"\"];
  tangoFileInfo *currentDir = [tangoFileInfo rootFileInfoForConnection:self];
  NSLog(@"CHUNK TOTAL [%d]",[chunks count]);
  
  for (int i = 0; i < [chunks count]; i++) {
      NSLog(@"CHUNK [%d]:%@ inside <%@>",i,[chunks objectAtIndex:i],[currentDir name]);
      currentDir = [self fileInfoFromName:[chunks objectAtIndex:i] inFolder:currentDir];
  
  ```
  //The path does not exist, so it should stop
  if (currentDir == nil) {
      return nil;
  } else {
      NSLog(@"CHUNK [%d] WAS FOUND:%@",i,[chunks objectAtIndex:i]);
  }
  ```
  
  }
  return currentDir;
  }
  '''

**Comment by devMan470** [comment]
Has anyone be able to resolve this issue? I notice that if I have more than 80 folder in the root directory I reach the

 if (resp_total_data_count != resp_data_count) condition.

If anyone has some insight on how to fix this please post it. Thanks

**Comment by pedrozaj** [comment]
Did anyone resolve this issue? I have a directory that can have up to 400 files but I can only function properly up to 86 files.  Hit the same error if (resp_total_data_count != resp_data_count

**Comment by pedrozaj** [comment]
I was able to fix the problem but only for a pre-defined max number of files to show.  Worked for my case as the max number of files I would ever have in the folder I'm looking in is 500 but it would be nice to have it be unlimited.
